version: "3"

services:
  golang_server:
      build: ../go_task
      container_name : go_task
      restart: always
      volumes:
        - ./go_task/src:/var/src
        - ./go_task/log:/var/log
      environment:
        TZ: "Asia/Tokyo"
      ports:
        - "3033:3033"
      tty: true
  python_server:
      build: ../arkansas
      container_name: arkansas
      restart: always
      volumes:
        - ../arkansas/app:/arkansas/app
        - ../arkansas/log:/arkansas/log
      environment:
        TZ: "Asia/Tokyo"
      ports:
        - "3034:3034"
      tty: true